apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  # image: "otel/opentelemetry-collector-contrib:0.78.0"
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
            endpoint: "0.0.0.0:3030"

    processors:
      batch:
        timeout: 1s

    exporters:
      logging:
        verbosity: detailed
      loki:
        endpoint: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
      prometheus:
      # local port open
        endpoint: "0.0.0.0:8889"

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
        traces:
          receivers: [otlp]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          exporters: [prometheus]